name: Publish

on:
  push:
    branches: [ main ]

jobs:
  publish:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '11'
          cache: 'maven'
      - run: |
          mvn package \
            --no-transfer-progress \
            -Dquarkus.application.version=${GITHUB_SHA} \
            -Dquarkus.container-image.username=${{ secrets.CONTAINER_USERNAME }} \
            -Dquarkus.container-image.password=${{ secrets.CONTAINER_PASSWORD }} \
            -Dquarkus.kubernetes-client.master-url=${{ secrets.KUBERNETES_MASTER }} \
            -Dquarkus.kubernetes-client.namespace=${{ secrets.KUBERNETES_NAMESPACE }} \
            -Dquarkus.kubernetes-client.token=${{ secrets.KUBERNETES_TOKEN }} \
            -Dquarkus.kubernetes.deploy=true

      - run: |
          kubectl --help
